export const sunflowerLanguages = [
  "Luganda",
  "Runyankore",
  "Ateso",
  "Swahili",
  "Lugbara",
  "Acholi",
  "English",
  "Rutooro",
  "Kinyarwanda",
  "Rukiga",
  "Lumasaba",
  "Samia",
  "Lusoga",
  "Runyoro",
  "Rukonjo",
  "Lango",
  "Lugwere",
  "Karamojong",
  "Lunyole",
  "Lugungu",
  "Bari",
  "Kupsabiny",
  "Ruruuli",
  "Kakwa",
  "Kumam",
  "Lubwisi",
  "Aringa",
  "Kwamba",
  "Dhopadhola",
  "Alur",
  "Ma'di",
  "Pokot",
] as const;

export type SunflowerLanguage = (typeof sunflowerLanguages)[number];
